backend = "glx";
vsync = true;
use-damage = true;

shadow = true;
shadow-radius = 8;
shadow-opacity = 0.15;
shadow-offset-x = -12;
shadow-offset-y = -12;
shadow-color = "#000000";

fading = true;
fade-in-step = 0.035;
fade-out-step = 0.035;

corner-radius = 7;
round-borders = 1;

inactive-opacity-override = false;
detect-client-opacity = true;

blur-method = "dual_kawase";
blur-strength = 8;
