#!/bin/sh

# exec
## deamons
sxhkd &
picom &
polybar &
clipmenud &
dunst &
## wallpapers
[ -f "$HOME/.fehbg" ] && "$HOME/.fehbg" &
## workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9 &
## keyboard layouts
setxkbmap -layout "us,ru" -option "grp:win_space_toggle" & ## you can disable this
## env
export QT_QPA_PLATFORMTHEME=qt6ct &
export CM_LAUNCHER="dmenu -i -l 10 -nb '#1e1e2e' -nf '#cdd6f4' -sb '#89b4fa' -sf '#11111b'"
export CM_HISTLENGTH=100

# windows
bspc config borde_width 1
bspc config window_gap 2
bspc config split_ratio 0.5

bspc config initial_polarity first_child
bspc config removal_adjustment true

bspc config honor_size_hints true
bspc config center_pseudo_tiled true

# mouse
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action3 resize_corner
bspc config click_to_focus button1
bspc config swallow_first_click false
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

# style
bspc config normal_border_color "#282c34"
bspc config active_border_color "#32363e"
bspc config focused_border_color "#abb2bf"

bspc config borderless_monocle false
bspc config gapless_monocle true
bspc config single_monocle true
bspc config paddingless_monocle true
bspc config paddingless_fullscreen true

# padding / gaps
bspc config top_padding 2
bspc config bottom_padding 2
bspc config left_padding 2
bspc config right_padding 2

# monitors / workspaces
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# layout
bspc config layout tiled
