#!/bin/sh

# exec
## keybind deamon
sxhkd &
## wallpapers
[ -f "$HOME/.fehbg" ] && "$HOME/.fehbg" &

bspc query -d 1 2 3 4 5 6 7 8 9

# windows
bspc config borde_width 1
bspc config window_gap 2
bspc config split_ratio 0.5

bspc config initial_polarity first_child
bspc config removal_adjustment true

bspc config honor_size_hints true
bspc config center_pseudo_tiled true

# mouse
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action3 resize_corner
bspc config click_to_focus button1
bspc config swallow_first_click false
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

# style
bspc config normal_border_color "#474747"
bspc config active_border_color "#cfcfcf"
bspc config focused_border_color "#ffffff"

bspc config borderless_monocle false
bspc config gapless_monocle true
bspc config single_monocle true
bspc config paddingless_monocle true
bspc config paddingless_fullscreen true

# padding / gaps
bspc config top_padding 2
bspc config bottom_padding 2
bspc config left_padding 2
bspc config right_padding 2

# monitors / workspaces
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# layout
bspc config layout tiled
